version: '3.7'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  issuer:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ldej.nl/issuer
    depends_on:
      - db
    ports:
      - "11000:11000"
      - "8000:8000"
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=3